const ORDER_DETAILS_ACTION_TYPES = {
  CREATE_ORDER_START: 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE'
};

export default ORDER_DETAILS_ACTION_TYPES;