const BURGER_INGREDIENTS_ACTION_TYPES = {
  FETCH_INGREDIENTS_START: 'burger-ingredients/FETCH_INGREDIENTS_START',
  FETCH_INGREDIENTS_SUCCESS: 'burger-ingredients/FETCH_INGREDIENTS_SUCCESS',
  FETCH_INGREDIENTS_FAILURE: 'burger-ingredients/FETCH_INGREDIENTS_FAILURE',
  ADD_INGREDIENT: 'burger-ingredients/ADD_INGREDIENT',
  DELETE_INGREDIENT: 'burger-ingredients/DELETE_INGREDIENT',
};

export default BURGER_INGREDIENTS_ACTION_TYPES;

